spring:
  application:
    name: ai-news-portal
  datasource:
    url: jdbc:sqlite:./data.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  servlet:
    multipart:
      enabled: false

server:
  port: 8080

logging:
  level:
    com.ainews: INFO
